// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function IsDir(arg1) {
  return window['go']['main']['App']['IsDir'](arg1);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function OpenLink(arg1) {
  return window['go']['main']['App']['OpenLink'](arg1);
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveExport(arg1, arg2) {
  return window['go']['main']['App']['SaveExport'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function StartupPaths() {
  return window['go']['main']['App']['StartupPaths']();
}

export function StatFile(arg1) {
  return window['go']['main']['App']['StatFile'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
