// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function IsDir(arg1:string):Promise<boolean>;

export function ListDir(arg1:string):Promise<Array<main.Entry>>;

export function OpenLink(arg1:string):Promise<void>;

export function PickFiles():Promise<Array<string>>;

export function PickFolder():Promise<string>;

export function ReadFile(arg1:string):Promise<main.FileData>;

export function SaveExport(arg1:string,arg2:string):Promise<string>;

export function StartupPaths():Promise<Array<string>>;

export function StatFile(arg1:string):Promise<number>;

export function WriteFile(arg1:string,arg2:string):Promise<number>;
